# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'navrh2.ui'
#
# WARNING! All changes made in this file will be lost!


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        TabWidget.setEnabled(True)
        TabWidget.resize(794, 589)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TabWidget.sizePolicy().hasHeightForWidth())
        TabWidget.setSizePolicy(sizePolicy)
        TabWidget.setMinimumSize(QtCore.QSize(400, 200))
        TabWidget.setAutoFillBackground(False)
        self.tab_Regions = QtWidgets.QWidget()
        self.tab_Regions.setEnabled(True)
        self.tab_Regions.setMinimumSize(QtCore.QSize(794, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.tab_Regions.setFont(font)
        self.tab_Regions.setObjectName("tab_Regions")
        self.pushButton_Regions_Next = QtWidgets.QPushButton(self.tab_Regions)
        self.pushButton_Regions_Next.setGeometry(QtCore.QRect(660, 520, 99, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_Regions_Next.setFont(font)
        self.pushButton_Regions_Next.setObjectName("pushButton_Regions_Next")
        self.label_MainRegions = QtWidgets.QLabel(self.tab_Regions)
        self.label_MainRegions.setGeometry(QtCore.QRect(50, 20, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_MainRegions.setFont(font)
        self.label_MainRegions.setObjectName("label_MainRegions")
        self.comboBox_MainRegion = QtWidgets.QComboBox(self.tab_Regions)
        self.comboBox_MainRegion.setGeometry(QtCore.QRect(50, 50, 251, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_MainRegion.setFont(font)
        self.comboBox_MainRegion.setEditable(False)
        self.comboBox_MainRegion.setCurrentText("")
        self.comboBox_MainRegion.setObjectName("comboBox_MainRegion")
        self.label_phaseRegion = QtWidgets.QLabel(self.tab_Regions)
        self.label_phaseRegion.setGeometry(QtCore.QRect(50, 90, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_phaseRegion.setFont(font)
        self.label_phaseRegion.setObjectName("label_phaseRegion")
        self.comboBox_IterationRegion = QtWidgets.QComboBox(self.tab_Regions)
        self.comboBox_IterationRegion.setGeometry(QtCore.QRect(50, 120, 251, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_IterationRegion.setFont(font)
        self.comboBox_IterationRegion.setEditable(False)
        self.comboBox_IterationRegion.setObjectName("comboBox_IterationRegion")
        self.widget_nested_regions = QtWidgets.QWidget(self.tab_Regions)
        self.widget_nested_regions.setGeometry(QtCore.QRect(360, 50, 401, 421))
        self.widget_nested_regions.setObjectName("widget_nested_regions")
        self.frame_nested_regions = QtWidgets.QFrame(self.widget_nested_regions)
        self.frame_nested_regions.setGeometry(QtCore.QRect(0, 0, 401, 421))
        self.frame_nested_regions.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_nested_regions.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_nested_regions.setObjectName("frame_nested_regions")
        self.label_NestedRegions = QtWidgets.QLabel(self.tab_Regions)
        self.label_NestedRegions.setGeometry(QtCore.QRect(360, 20, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_NestedRegions.setFont(font)
        self.label_NestedRegions.setObjectName("label_NestedRegions")
        self.pushButton_Regions_All = QtWidgets.QPushButton(self.tab_Regions)
        self.pushButton_Regions_All.setGeometry(QtCore.QRect(660, 480, 99, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_Regions_All.setFont(font)
        self.pushButton_Regions_All.setObjectName("pushButton_Regions_All")
        self.pushButton_tree = QtWidgets.QPushButton(self.tab_Regions)
        self.pushButton_tree.setGeometry(QtCore.QRect(50, 290, 0, 0)) # QRect(50, 290, 151, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_tree.setFont(font)
        self.pushButton_tree.setObjectName("pushButton_tree")
        self.pushButton_filter = QtWidgets.QPushButton(self.tab_Regions)
        self.pushButton_filter.setGeometry(QtCore.QRect(50, 240, 99, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_filter.setFont(font)
        self.pushButton_filter.setObjectName("pushButton_filter")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.tab_Regions)
        self.doubleSpinBox.setGeometry(QtCore.QRect(50, 200, 121, 26))
        self.doubleSpinBox.setDecimals(8)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.label_filter = QtWidgets.QLabel(self.tab_Regions)
        self.label_filter.setGeometry(QtCore.QRect(50, 170, 231, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_filter.setFont(font)
        self.label_filter.setObjectName("label_filter")
        self.label_sec = QtWidgets.QLabel(self.tab_Regions)
        self.label_sec.setGeometry(QtCore.QRect(180, 200, 31, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_sec.setFont(font)
        self.label_sec.setObjectName("label_sec")
        TabWidget.addTab(self.tab_Regions, "")
        self.tab_DataParameters = QtWidgets.QWidget()
        self.tab_DataParameters.setObjectName("tab_DataParameters")
        self.pushButton_DataParam_Prev = QtWidgets.QPushButton(self.tab_DataParameters)
        self.pushButton_DataParam_Prev.setGeometry(QtCore.QRect(460, 520, 99, 27))
        self.pushButton_DataParam_Prev.setObjectName("pushButton_DataParam_Prev")
        self.label_ylabel = QtWidgets.QLabel(self.tab_DataParameters)
        self.label_ylabel.setGeometry(QtCore.QRect(50, 20, 150, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_ylabel.setFont(font)
        self.label_ylabel.setObjectName("label_ylabel")
        self.widget_parameters = QtWidgets.QWidget(self.tab_DataParameters)
        self.widget_parameters.setGeometry(QtCore.QRect(50, 210, 711, 300))
        self.widget_parameters.setObjectName("widget_parameters")
        self.frame_parameters = QtWidgets.QFrame(self.widget_parameters)
        self.frame_parameters.setGeometry(QtCore.QRect(0, 0, 711, 300))
        self.frame_parameters.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_parameters.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_parameters.setObjectName("frame_parameters")
        self.label_parameters = QtWidgets.QLabel(self.tab_DataParameters)
        self.label_parameters.setGeometry(QtCore.QRect(50, 190, 150, 27))


        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_parameters.setFont(font)
        self.label_parameters.setObjectName("label_parameters")

        self.treeWidget_ylabel = QtWidgets.QTreeWidget(self.tab_DataParameters)
        self.treeWidget_ylabel.setGeometry(QtCore.QRect(50, 50, 471, 140))
        self.treeWidget_ylabel.setObjectName("treeWidget_ylabel")
        self.treeWidget_ylabel.headerItem().setText(0, "1")
        self.treeWidget_ylabel.header().setVisible(False)
        self.checkBox_time_energy_vars = QtWidgets.QCheckBox(self.tab_DataParameters)
        self.checkBox_time_energy_vars.setGeometry(QtCore.QRect(540, 20, 191, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_time_energy_vars.setFont(font)
        self.checkBox_time_energy_vars.setObjectName("checkBox_time_energy_vars")
        self.frame_time_energy = QtWidgets.QFrame(self.tab_DataParameters)
        self.frame_time_energy.setGeometry(QtCore.QRect(540, 50, 221, 141))
        self.frame_time_energy.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_time_energy.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_time_energy.setObjectName("frame_time_energy")
        self.lineEdit_baseline = QtWidgets.QLineEdit(self.frame_time_energy)
        self.lineEdit_baseline.setGeometry(QtCore.QRect(80, 110, 113, 25))
        self.lineEdit_baseline.setObjectName("lineEdit_baseline")
        self.comboBox_time = QtWidgets.QComboBox(self.frame_time_energy)
        self.comboBox_time.setEnabled(True)
        self.comboBox_time.setGeometry(QtCore.QRect(0, 20, 221, 25))
        self.comboBox_time.setObjectName("comboBox_time")
        self.label_Baseline = QtWidgets.QLabel(self.frame_time_energy)
        self.label_Baseline.setGeometry(QtCore.QRect(0, 110, 81, 27))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_Baseline.setFont(font)
        self.label_Baseline.setObjectName("label_Baseline")
        self.label_energy = QtWidgets.QLabel(self.frame_time_energy)
        self.label_energy.setEnabled(True)
        self.label_energy.setGeometry(QtCore.QRect(0, 50, 67, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_energy.setFont(font)
        self.label_energy.setObjectName("label_energy")
        self.comboBox_energy = QtWidgets.QComboBox(self.frame_time_energy)
        self.comboBox_energy.setEnabled(True)
        self.comboBox_energy.setGeometry(QtCore.QRect(0, 70, 221, 25))
        self.comboBox_energy.setObjectName("comboBox_energy")
        self.label_W = QtWidgets.QLabel(self.frame_time_energy)
        self.label_W.setGeometry(QtCore.QRect(200, 110, 31, 27))
        self.label_W.setObjectName("label_W")
        self.label_time = QtWidgets.QLabel(self.frame_time_energy)
        self.label_time.setEnabled(True)
        self.label_time.setGeometry(QtCore.QRect(0, 0, 67, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_time.setFont(font)
        self.label_time.setObjectName("label_time")
        self.pushButton_run = QtWidgets.QPushButton(self.tab_DataParameters)
        self.pushButton_run.setGeometry(QtCore.QRect(570, 520, 191, 27))
        self.pushButton_run.setObjectName("pushButton_run")
        TabWidget.addTab(self.tab_DataParameters, "")

        self.label_note = QtWidgets.QLabel(self.tab_DataParameters)
        self.label_note.setGeometry(50, 520, 450, 27)
        self.label_note.setFont(font)
        self.label_note.setObjectName("label_note")
        self.label_note.setStyleSheet('color: red')

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        _translate = QtCore.QCoreApplication.translate
        TabWidget.setWindowTitle(_translate("TabWidget", "RADAR configuration"))
        self.pushButton_Regions_Next.setText(_translate("TabWidget", "Next"))
        self.label_MainRegions.setText(_translate("TabWidget", "Main region"))
        self.label_phaseRegion.setText(_translate("TabWidget", "Phase region"))
        self.label_NestedRegions.setText(_translate("TabWidget", "Nested regions"))
        self.pushButton_Regions_All.setText(_translate("TabWidget", "Select all"))
        self.pushButton_tree.setText(_translate("TabWidget", "Show region tree"))
        self.pushButton_filter.setText(_translate("TabWidget", "Apply filter"))
        self.label_filter.setText(_translate("TabWidget", "Filter nested regions by time"))
        self.label_sec.setText(_translate("TabWidget", "s"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_Regions), _translate("TabWidget", "Regions"))
        self.pushButton_DataParam_Prev.setText(_translate("TabWidget", "Previous"))
        self.label_ylabel.setText(_translate("TabWidget", "y label"))
        self.label_parameters.setText(_translate("TabWidget", "Parameters"))
        self.checkBox_time_energy_vars.setText(_translate("TabWidget", "Time-energy variables"))
        self.label_Baseline.setText(_translate("TabWidget", "Baseline"))
        self.label_energy.setText(_translate("TabWidget", "Energy"))
        self.label_W.setText(_translate("TabWidget", "W"))
        self.label_time.setText(_translate("TabWidget", "Time"))
        self.pushButton_run.setText(_translate("TabWidget", "Run RADAR analysis"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_DataParameters), _translate("TabWidget", "Data parameters"))
        self.label_note.setText(_translate("TabWidget", " "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TabWidget = QtWidgets.QTabWidget()
    ui = Ui_TabWidget()
    ui.setupUi(TabWidget)
    TabWidget.show()
    sys.exit(app.exec_())
