# -*- coding: utf-8 -*-

from src import design_main_menu
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TimeMenu(object):
    def setupUi(self, MainMenu):
        MainMenu.setObjectName("Timeline Menu")
        MainMenu.resize(267, 740)
        self.centralwidget = QtWidgets.QWidget(MainMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_analysis = QtWidgets.QFrame(self.centralwidget)
        self.frame_analysis.setGeometry(QtCore.QRect(10, 10, 251, 411))
        self.frame_analysis.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_analysis.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_analysis.setObjectName("frame_analysis")
        self.pushButton_runtime_suma_plot = QtWidgets.QPushButton(self.frame_analysis)
        
        self.pushButton_runtime_suma_plot.setGeometry(QtCore.QRect(10, 110, 231, 40))
        self.pushButton_runtime_suma_plot.setObjectName("pushButton_runtime_suma_plot")

        self.pushButton_timeline = QtWidgets.QPushButton(self.frame_analysis)
        self.pushButton_timeline.setGeometry(QtCore.QRect(10, 160, 231, 40))
        self.pushButton_timeline.setObjectName("pushButton_timeline")
        self.pushButton_runtime_reg_plot = QtWidgets.QPushButton(self.frame_analysis)
        self.pushButton_runtime_reg_plot.setGeometry(QtCore.QRect(10, 60, 231, 40))
        self.pushButton_runtime_reg_plot.setObjectName("pushButton_runtime_reg_plot")
        self.pushButton_calltree = QtWidgets.QPushButton(self.frame_analysis)
        self.pushButton_calltree.setGeometry(QtCore.QRect(10, 10, 231, 40))
        self.pushButton_calltree.setObjectName("pushButton_calltree")
        self.pushButton_average_freq_reg_plot = QtWidgets.QPushButton(self.frame_analysis)
        self.pushButton_average_freq_reg_plot.setGeometry(QtCore.QRect(10, 210, 231, 40))
        self.pushButton_average_freq_reg_plot.setObjectName("pushButton_average_freq_reg_plot")
        self.pushButton_term_reg_plot= QtWidgets.QPushButton(self.frame_analysis)
        self.pushButton_term_reg_plot.setGeometry(QtCore.QRect(10, 260, 231, 40))
        self.pushButton_term_reg_plot.setObjectName("pushButton_term_reg_plot")
        self.pushButton_all_freq_plot = QtWidgets.QPushButton(self.frame_analysis)
        self.pushButton_all_freq_plot.setGeometry(QtCore.QRect(10, 310, 231, 40))
        self.pushButton_all_freq_plot.setObjectName("pushButton_all_freq_plot")
        self.pushButton_all_term_plot = QtWidgets.QPushButton(self.frame_analysis)
        self.pushButton_all_term_plot.setGeometry(QtCore.QRect(10, 360, 231, 40))
        self.pushButton_all_term_plot.setObjectName("pushButton_all_term_plot")
        self.frame_options = QtWidgets.QFrame(self.centralwidget)
        self.frame_options.setGeometry(QtCore.QRect(10, 430, 251, 211))
        self.frame_options.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_options.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_options.setObjectName("frame_options")
        self.pushButton_generate_latex = QtWidgets.QPushButton(self.frame_options)
        self.pushButton_generate_latex.setGeometry(QtCore.QRect(10, 10, 231, 40))
        self.pushButton_generate_latex.setObjectName("pushButton_generate_latex")
        self.pushButton_generate_meric = QtWidgets.QPushButton(self.frame_options)
        self.pushButton_generate_meric.setGeometry(QtCore.QRect(10, 60, 231, 40))
        self.pushButton_generate_meric.setObjectName("pushButton_generate_meric")
        self.pushButton_edit_radar = QtWidgets.QPushButton(self.frame_options)
        self.pushButton_edit_radar.setGeometry(QtCore.QRect(10, 110, 231, 40))
        self.pushButton_edit_radar.setObjectName("pushButton_edit_radar")
        self.pushButton_save_radar = QtWidgets.QPushButton(self.frame_options)
        self.pushButton_save_radar.setGeometry(QtCore.QRect(10, 160, 231, 40))
        self.pushButton_save_radar.setObjectName("pushButton_save_radar")
        self.frame_restart = QtWidgets.QFrame(self.centralwidget)
        self.frame_restart.setGeometry(QtCore.QRect(10, 650, 251, 61))
        self.frame_restart.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_restart.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_restart.setObjectName("frame_restart")
        self.pushButton_restart = QtWidgets.QPushButton(self.frame_restart)
        self.pushButton_restart.setGeometry(QtCore.QRect(10, 10, 231, 40))
        self.pushButton_restart.setObjectName("pushButton_restart")
        self.frame_restart.raise_()
        self.frame_options.raise_()
        self.frame_analysis.raise_()
        # MainMenu.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainMenu)
        self.statusbar.setObjectName("statusbar")
        # MainMenu.setStatusBar(self.statusbar)

        self.retranslateUi(MainMenu)
        QtCore.QMetaObject.connectSlotsByName(MainMenu)

    def retranslateUi(self, MainMenu):
        _translate = QtCore.QCoreApplication.translate
        MainMenu.setWindowTitle(_translate("MainMenu", "Radar Timeline analysis"))
        self.pushButton_runtime_suma_plot.setText(_translate("MainMenu", "runtime_suma_plot"))
        self.pushButton_runtime_reg_plot.setText(_translate("MainMenu", "runtime_reg_plot"))
        self.pushButton_timeline.setText(_translate("MainMenu", "Timeline"))

        self.pushButton_calltree.setText(_translate("MainMenu", "calltree"))
        self.pushButton_average_freq_reg_plot.setText(_translate("MainMenu", "verage_freq_reg_plot"))
        self.pushButton_term_reg_plot.setText(_translate("MainMenu", "term_reg_plot"))
        self.pushButton_all_freq_plot.setText(_translate("MainMenu", "all_freq_plot"))
        self.pushButton_all_term_plot.setText(_translate("MainMenu", "all_term_plot"))
        self.pushButton_generate_latex.setText(_translate("MainMenu", "Generate LaTeX report"))
        self.pushButton_generate_meric.setText(_translate("MainMenu", "Generate MERIC config"))
        self.pushButton_edit_radar.setText(_translate("MainMenu", "Edit RADAR config"))
        self.pushButton_save_radar.setText(_translate("MainMenu", "Save current RADAR config"))
        self.pushButton_restart.setText(_translate("MainMenu", "Restart Radar analysis"))


